#!/usr/bin/env node
// Search plugins (every installed marketplace), all ECC skills, the catalog and skills.sh
// (the open community skill directory) for keywords.
//   node find.mjs video caption [--all] [--offline]
import { execFileSync } from 'node:child_process'
import { existsSync, readdirSync, readFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const args = process.argv.slice(2)
const showAll = args.includes('--all')
const offline = args.includes('--offline')
const words = args.filter((a) => !a.startsWith('--')).map((w) => w.toLowerCase())
if (!words.length) {
  console.error('Usage: node find.mjs <keyword> [<keyword>...] [--all] [--offline]')
  process.exit(1)
}

const score = (text) => {
  const t = text.toLowerCase()
  return words.reduce((n, w) => n + (t.includes(w) ? 1 : 0), 0)
}
const limit = showAll ? Infinity : 12
const results = []

// Plugins from every marketplace Claude Code has cloned locally.
const claudeDir = process.env.CLAUDE_CONFIG_DIR || join(homedir(), '.claude')
const mpDir = join(claudeDir, 'plugins', 'marketplaces')
if (existsSync(mpDir)) {
  for (const mp of readdirSync(mpDir)) {
    const f = join(mpDir, mp, '.claude-plugin', 'marketplace.json')
    if (!existsSync(f)) continue
    let data
    try { data = JSON.parse(readFileSync(f, 'utf8')) } catch { continue }
    for (const p of data.plugins ?? []) {
      const s = score(`${p.name} ${p.description ?? ''} ${(p.keywords ?? []).join(' ')} ${p.category ?? ''}`)
      if (s) results.push({ kind: 'plugin', s, name: `${p.name}@${data.name ?? mp}`, desc: p.description ?? '',
        add: `claude plugin install ${p.name}@${data.name ?? mp} --scope project` })
    }
  }
}
if (!results.length && !existsSync(mpDir)) {
  // Cloud sessions may not have the marketplace cloned: read the official catalog from GitHub.
  try {
    const raw = execFileSync('curl', ['-fsSL', '--max-time', '20', 'https://raw.githubusercontent.com/anthropics/claude-plugins-official/main/.claude-plugin/marketplace.json'], { encoding: 'utf8' })
    for (const p of JSON.parse(raw).plugins ?? []) {
      const s = score(`${p.name} ${p.description ?? ''} ${(p.keywords ?? []).join(' ')} ${p.category ?? ''}`)
      if (s) results.push({ kind: 'plugin', s, name: `${p.name}@claude-plugins-official`, desc: p.description ?? '',
        add: `claude plugin install ${p.name}@claude-plugins-official --scope project` })
    }
  } catch {
    console.warn(`(no plugin marketplaces under ${mpDir} and GitHub unreachable; run Claude Code once)`)
  }
}

// ECC skills (index generated by scripts/sync-ecc.mjs in yskills/claude-setup).
const idx = JSON.parse(readFileSync(join(here, '..', 'ecc-index.json'), 'utf8'))
for (const sk of idx.skills) {
  const s = score(`${sk.name} ${sk.description}`)
  if (s) results.push({ kind: 'ecc skill', s, name: sk.name, desc: sk.description,
    add: sk.installedGlobally ? '(already installed globally)' : `node ${join(here, 'add-skill.mjs')} ${sk.name}` })
}

// Catalog lines that mention the keywords.
const catDir = join(here, '..', 'catalog')
const catHits = []
for (const f of readdirSync(catDir)) {
  for (const line of readFileSync(join(catDir, f), 'utf8').split('\n')) {
    const s = score(line)
    if (s && line.startsWith('|')) catHits.push({ s, line: `${f}: ${line.slice(0, 220)}` })
  }
}

for (const kind of ['plugin', 'ecc skill']) {
  const list = results.filter((r) => r.kind === kind).sort((a, b) => b.s - a.s).slice(0, limit)
  console.log(`\n## ${kind}s (${list.length}${showAll ? '' : ' best'})`)
  for (const r of list) console.log(`- ${r.name}: ${r.desc.slice(0, 140)}\n    ${r.add}`)
}
console.log(`\n## catalog lines`)
for (const h of catHits.sort((a, b) => b.s - a.s).slice(0, limit)) console.log(`- ${h.line}`)

// skills.sh via its CLI, pinned (read 2026-10-05; it only queries the directory, installs nothing).
// skills.sh: hundreds of thousands of community skills, unvetted. Many are junk or unsafe, so
// every hit is a lead to read before installing (toolbox SKILL.md, step 3), never an install.
if (!offline) {
  console.log(`\n## skills.sh (community, unvetted: read before installing)`)
  try {
    // One query per keyword (at most 4): skills.sh matches a whole phrase and sorts by installs.
    const hits = new Map()
    for (const word of words.slice(0, 4)) {
      const raw = execFileSync('npx', ['-y', 'skills@1.7.0', 'find', word], { encoding: 'utf8', timeout: 90_000, stdio: ['ignore', 'pipe', 'ignore'] })
      const lines = raw.replace(/\x1b\[[0-9;]*m/g, '').split('\n').map((l) => l.trim()).filter(Boolean)
      for (let i = 0; i < lines.length; i++) {
        const m = lines[i].match(/^(\S+@\S+)\s+(.*installs.*)$/)
        if (m && !hits.has(m[1])) hits.set(m[1], { s: score(m[1]), line: `- ${m[1]} (${m[2]})${lines[i + 1]?.startsWith('└') ? `\n    ${lines[i + 1].slice(1).trim()}` : ''}` })
      }
    }
    // Keep hits whose name carries a keyword; the directory's own order is by popularity.
    const relevant = [...hits.values()].filter((h) => showAll || h.s).sort((a, b) => b.s - a.s)
    console.log(relevant.slice(0, limit).map((h) => h.line).join('\n') || '(no hits)')
  } catch {
    console.log('(skills.sh unreachable; run `npx skills find <query>` by hand, or pass --offline)')
  }
}
console.log(`\nAlso search the claude.ai Anthropic Directory (plugins, skills, connectors like Figma, Canva, Adobe): in cloud threads with the SearchPlugins, SearchSkills and SearchMcpRegistry tools; on the PC in claude.ai > Customize.`)
