#!/usr/bin/env node
// Search plugins (every installed marketplace) and all ECC skills for keywords.
//   node find.mjs video caption [--all]
import { execFileSync } from 'node:child_process'
import { existsSync, readdirSync, readFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const args = process.argv.slice(2)
const showAll = args.includes('--all')
const words = args.filter((a) => !a.startsWith('--')).map((w) => w.toLowerCase())
if (!words.length) {
  console.error('Usage: node find.mjs <keyword> [<keyword>...] [--all]')
  process.exit(1)
}

const score = (text) => {
  const t = text.toLowerCase()
  return words.reduce((n, w) => n + (t.includes(w) ? 1 : 0), 0)
}
const limit = showAll ? Infinity : 12
const results = []

// Plugins from every marketplace Claude Code has cloned locally.
const claudeDir = process.env.CLAUDE_CONFIG_DIR || join(homedir(), '.claude')
const mpDir = join(claudeDir, 'plugins', 'marketplaces')
if (existsSync(mpDir)) {
  for (const mp of readdirSync(mpDir)) {
    const f = join(mpDir, mp, '.claude-plugin', 'marketplace.json')
    if (!existsSync(f)) continue
    let data
    try { data = JSON.parse(readFileSync(f, 'utf8')) } catch { continue }
    for (const p of data.plugins ?? []) {
      const s = score(`${p.name} ${p.description ?? ''} ${(p.keywords ?? []).join(' ')} ${p.category ?? ''}`)
      if (s) results.push({ kind: 'plugin', s, name: `${p.name}@${data.name ?? mp}`, desc: p.description ?? '',
        add: `claude plugin install ${p.name}@${data.name ?? mp} --scope project` })
    }
  }
}
if (!results.length && !existsSync(mpDir)) {
  // Cloud sessions may not have the marketplace cloned: read the official catalog from GitHub.
  try {
    const raw = execFileSync('curl', ['-fsSL', '--max-time', '20', 'https://raw.githubusercontent.com/anthropics/claude-plugins-official/main/.claude-plugin/marketplace.json'], { encoding: 'utf8' })
    for (const p of JSON.parse(raw).plugins ?? []) {
      const s = score(`${p.name} ${p.description ?? ''} ${(p.keywords ?? []).join(' ')} ${p.category ?? ''}`)
      if (s) results.push({ kind: 'plugin', s, name: `${p.name}@claude-plugins-official`, desc: p.description ?? '',
        add: `claude plugin install ${p.name}@claude-plugins-official --scope project` })
    }
  } catch {
    console.warn(`(no plugin marketplaces under ${mpDir} and GitHub unreachable; run Claude Code once)`)
  }
}

// ECC skills (index generated by scripts/sync-ecc.mjs in yskills/claude-setup).
const idx = JSON.parse(readFileSync(join(here, '..', 'ecc-index.json'), 'utf8'))
for (const sk of idx.skills) {
  const s = score(`${sk.name} ${sk.description}`)
  if (s) results.push({ kind: 'ecc skill', s, name: sk.name, desc: sk.description,
    add: sk.installedGlobally ? '(already installed globally)' : `node ${join(here, 'add-skill.mjs')} ${sk.name}` })
}

// Catalog lines that mention the keywords.
const catDir = join(here, '..', 'catalog')
const catHits = []
for (const f of readdirSync(catDir)) {
  for (const line of readFileSync(join(catDir, f), 'utf8').split('\n')) {
    const s = score(line)
    if (s && line.startsWith('|')) catHits.push({ s, line: `${f}: ${line.slice(0, 220)}` })
  }
}

for (const kind of ['plugin', 'ecc skill']) {
  const list = results.filter((r) => r.kind === kind).sort((a, b) => b.s - a.s).slice(0, limit)
  console.log(`\n## ${kind}s (${list.length}${showAll ? '' : ' best'})`)
  for (const r of list) console.log(`- ${r.name}: ${r.desc.slice(0, 140)}\n    ${r.add}`)
}
console.log(`\n## catalog lines`)
for (const h of catHits.sort((a, b) => b.s - a.s).slice(0, limit)) console.log(`- ${h.line}`)
